### ISSUE TITLE
Filename preservation options

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#204]
As discussed in today's videochat:

1. The spec in draft-4 is clarified: filenames are not guaranteed to be preserved; `cwltool` scrambles file names to enforce this
2. As in 1, but a flag is added to `cwltool` to turn off filename scrambling.
3. As in 2, but a new `Requirement` is added to the spec that can be added to tools or workflows to indicate that filename preservation is required
4. The following metadata is exposed for each file: The entire provided filename, the base (up to the last period) of the provided filename, and the extension (everything after the last period) of the provided filename
5. Option `4` in combination with option `3`.

**Comment by tetron** [comment]
I keep going around in circles on this one.  Technically, platforms can do whatever they want, but arbitrarily changing filenames seems to violate the principal of least surprise.  It is definitely already the case that people are writing tools that rely on filename manipulations and likely will continue to do so.

**Comment by pgrosu** [comment]
Maybe we can simplify by having a filename defined just a `Path`, defined as:

```
<Path> ::= ListOf( <Content> )
```
where `Content` is defined as:

```
<Content> ::= ListOf( <Unicode character> )
```

So a change in filename would be defined as:

```
p:Path ⊢ f(f(...f( p )...)) : Path
```

Then we just keep adding to the `Path` list any time there is a change in the filename, and peek at the last entry for the current filename.  And if necessary, then conflicts can be easily examined by looking between the `Path` lists for matches of equality.

The same idea can be extended for defining a `File` as:

```
p:Path, c:Content ⊢ C(p, c): File

or 

<File> ::= ListOf( <Path>, <Content> ) | <Path> <Content>
```

~p

**Comment by jmchilton** [comment]
> Technically, platforms can do whatever they want, but arbitrarily changing filenames seems to violate the principal of least surprise.

Galaxy has no concept of file names - I'm not willing to concede that we change them or that violates the concept of least surprise - they never exist. A user pastes some text in a box to create a file - what was the file's name? Galaxy might run tools on that file on many different clusters each with different mounts - there is never a name or a path for that file from a tool or workflow perspective.  From a Galaxy perspective, I'd have to answer questions like is the file name editable, how do users modify the file name if yes, are the there data privacy concerns with sharing for instance if no.

Galaxy was an existing and useful workflow platform when this effort started and I've had to add a bunch of concepts and abstractions to it to attempt to implement this standard - some of these are okay but each represents a step beyond what is minimally needed - this however is so fundamental and really feels like it is going so far. The goal was I thought to provide a minimal base spec and allow extensions with requirements - clearly one can make very popular tool execution or workflow platform without a concept of a file name. Galaxy isn't the only one either by the way - many web service frameworks have concepts of data without concepts of file names.

I strongly feel we should introduce a "requirement" for this or do something like ``4`` described above - and if we do I will eagerly and happily do my best to provide this but it will be a crappy, hacky implementation of it. The mere fact that the implementation will be hacky means this concept doesn't gel well with a very reasonable data model (and user interaction model) for workflow systems. I know most of the people involved with this project consider Galaxy's data model... let us nicely say quirky - but it is the oldest, most sophisticated, and most mature of those that have had serious work toward CWL implementation - the fact that this doesn't fit within that framework should be seen as a canary in the CWL mine (not as a Galaxy mine canary).

*All ways we define for transfer and consumption of metadata should be optional and should require explicit activation by the tool author.*

There are more pragmatic reasons also - against a lot of pressure (including from me initially) - the CWL builds command line arguments instead of shell commands. I liked this and participated because there is a real security upside to this. If we are going to force our platform to preserve and pass around filenames - we negate the security and usability upsides in a profound way. To the extent that if we don't care about pragmatic security concerns, I don't understand why we would continue to push back against just templating the whole command line. Many bioinformatics scripts execute other programs - and in my experience they generally do so in the same sloppy way the CWL prides itself on not doing things - so if we are guaranteeing preservation of problematic file names we are purposely introducing security and end-user usability problems. (I know that what I am arguing for introduces tool developer and workflow developer usability problems - but these parties are less important to me.)

**Comment by tetron** [comment]
Hi @jmchilton I really appreciate the input.  Like I said, I'm on the fence and still trying to work through the implications of various options.

The CWL model already treats files as immutable objects.  The "path" field is already somewhat opaque (files may be relocated, paths may be rewritten by the platform as necessary to map between container, host file system, shared filesystem, network resources, etc.) but tools do make decisions based on the base file name and/or filename extension.  The most recent conversations have been moving in the direction of a new field "location" which would be a fully opaque URI and having the "path" field only be meaningful when building command lines.

Within the platform itself, file (or "data sets") handling may be completely arbitrary.  However, in order to present them to tools, eventually they need to be materialized as files on the file system so they can be opened and read using normal POSIX syscalls.  At that point, a file path has to be assigned.

At issue here is how the logic of the command line tool wrapper and/or the tool itself depends on input file paths following certain expected patterns.  If file paths are opaque and given arbitrary (software generated) names, this breaks at least two common tool patterns:

 1. choosing behavior based on file extension (the entire `make` family tree is based on this idea)
 2. choosing an output filename based on the input file path (when originating from a human-meaningful input file name, and you need to get back a "regular file" which you intend to use outside the warm confines of your chosen workflow environment).

How are these cases handled in Galaxy?

If we can design suitable complementary features for the above cases (maybe based on the idea of making the file name and extension "metadata" rather than an intrinsic property) then I think it makes sense to relax the expectation that the name of the "file" produced by step 1 will be maintained when that "file" is passed to step 2.

**Comment by tetron** [comment]
I should mention, this needs to go together with the conversation about the proposed `Directory` type (#172, #201).  The `Directory` type may be the mechanism by which we assign filenames to things that need meaningful filenames in order for a given tool to work.

**Comment by mr-c** [comment]
Thank you John for your detailed comment, I really appreciate it.

@tetron Galaxy tool descriptions do file renaming as is needed by the underlying tool. I agree that the proposed `Directory` type will make this a lot easier. As for saving files, the Galaxy type system associates a (default) extension for each file type. This is not a feature that the EDAM ontology has, however IANA Media Types do have file extensions registered: http://www.iana.org/assignments/media-types/application/vnd.oxli.countgraph

**Comment by mr-c** [comment]
Notes from today's discussion:

1. CreateFileDef can already do renames

New proposal: default is random names; one new Requirement FilenamePreservation (which only preserves the name safely eliminating the POSIX SH shell metacharacters; the original file basename and extension (again the safe version) are available as properties on the File object

[Francois points out that some tools require "real" files, not symlinks]

**Comment by tetron** [comment]
@mr-c @jmchilton 

Proposed compromise:

The upcoming spec will indicate that file names should be preserved by default, as that is the de facto behavior right now.

The following spec version that change the behavior; it will not preserve file names by default.  Instead, we make the following changes:
* Add a PreserveFilenameRequirement
* Narrow the scope of secondaryFiles so that we can scramble the base name and still produce a correct secondary file name.
* Introduce the Directory type to correctly handle the more general case of data sets where file reference one another.

**Comment by mr-c** [comment]
:+1:
Pe 7 iun. 2016 6:20 p.m., "Peter Amstutz" <notifications@github.com> a
scris:

**Comment by jmchilton** [comment]
@tetron Can you describe your issue with updating the spec to indicate CWL files must match a certain whitelist-ing regex? This seems simple enough - I'm not sure the reference implementation would even need to enforce this - and would allay some of the security problems I see with 1.0.

**Comment by tetron** [comment]
@jmchilton To clarify, are you suggesting whitelisting file names in general, so if you try to use a filename called `**$(rm -rf /)**.txt` that results in a workflow failure?

I think I would be happy with this solution.  The problem I've trying to avoid introducing is having the runtime unilaterally mangle filenames in ways that break internal dependencies between files (e.g. if file A has a reference to file B, and we rename B to C then A has a broken reference)  This would avoid that problem by leaving well-behaved files with their original names.

Here's my new proposal (this supersedes my previous comment).  Add the following spec language: 

* When staging input files to present to a tool, the implementation MUST preserve the base name of input file, if available.  If no file name is available, the implementation MUST assign a file name.
* For security purposes, an implementation MAY check input file names and restrict them to a valid subset.  An illegal filename found on input MAY result in a workflow error.  Implementations are recommended to use the following regular expression ... (TBD)
* Filename validation MAY be disabled disabled at use option, if provided by the implementation.

**Comment by jmchilton** [comment]
@tetron This is a great compromise for draft 4/1.0. I don't have a good set of whitelist characters off the top of my head - I thought someone referenced one - I'll google around for it a bit.

**Comment by jmchilton** [comment]
My suggested regex would be suggesting whitelisting ``[\p{N}\p{L}\p{Pc}\p{Pd}\.]``. This is the unicode character equivalent of alphanumric characters, dashes, underscores, and the ASCII ``.``.

**Comment by mr-c** [comment]
We had talked about allowing all characters except the [POSIX shell metacharacters](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02): `|`,`&`, `;`, `<`, `>`, `(`,`)`, `$`,`` ` ``, `\`, `"`, `'`, `<space>`, `<tab>`, and `<newline>`.

**Comment by mr-c** [comment]
I like the inclusion approach. The best thought out list of "safe" unicode codepoints is probably the internationalized domain name rules at http://www.iana.org/assignments/idna-tables-6.3.0/idna-tables-6.3.0.xhtml

**Comment by mr-c** [comment]
Agreement: use the accept list, no mention of an override requirement in the spec

**Comment by mr-c** [comment]
Done in #243
