### ISSUE TITLE
investigate how bioboxes interface validators would play with cwl

### ISSUE THREAD

**Issue by avilella** [common-workflow-language/common-workflow-language#21]
https://github.com/bioboxes/rfc/issues/35

    f: [A] → [A] → [(K,V)]

Sorry @seandavi  I cross-posted the wrong issue for another project. Too many open tabs!! :-p

**Comment by seandavi** [comment]
You might also be interested in rbokeh, as it is in a similar space as plotly/shiny.

https://github.com/bokeh/rBokeh

For a more module approach in R, there is the htmlwidgets package.  A small community is starting to contribute javascript-based widgets for interactive data visualization.

http://www.htmlwidgets.org/

**Comment by tetron** [comment]
(deleted @seandavi comment intended for a different issue)

**Comment by avilella** [comment]
mentioning @michaelbarton and @pbelmann here so they see the issue.

**Comment by tetron** [comment]
It looks like the relevant bioboxes issues are bioboxes/rfc#61 and bioboxes/rfc#86 so I will leave some initial comments there.

**Comment by tetron** [comment]
@ntijanic posted an excellent writeup at bioboxes/rfc#61 already, so I'll respond here instead.

To summarize my understanding, the current approach taken by bioboxes is:
1. Execute the default command for the image, which is defined in the Dockerfile
2. Parameters are passed in by environment variables, but there is recognition that is inadequate
3. Inputs/output directories are bind mounted (I assume?)
4. The approach being discussed in bioboxes/rfc#61 is to design schemas for YAML files that describe valid input for categories of tools such as assemblers.  This input YAML will be made available to the wrapper script inside the container somehow.
5. the "biobox interface validator" is intended to test that a biobox image accepts the proper input YAML parameters and produces the correct output.

Please correct me if I'm wrong on any of these points.

Some commentary:
1. CWL doesn't require a default command for a Docker image.  This makes it easy to put multiple tools into one image.
2. CWL input parameters are converted and passed in as actual command line parameters for the underlying tool; CWL also supports "file definitions" where configuration files can be dynamically generated based on the input parameters and placed inside the container for use by the tool.
3. Inputs/output directories are also bind mounted in CWL, and input directories must be read only.
4. CWL does not currently have a concept of abstract interfaces where a category of tool (such as assemblers) declare that they support a common parameter definition in order to easily switch between tools.  This is a very interesting idea and one we would consider adding.
5. CWL uses Avro to describe the structure of YAML input and output parameters.  Input parameters are always validated on load.  For validating specific tool definition files and implementations, CWL has a conformance test suite which runs tools and checks for the correct command line and/or correct output.

**Comment by tetron** [comment]
A couple additional thoughts:
1. CWL does not (currently) define file types, so an input type can be "File" but not specifically a FASTQ file.  We want to use the https://github.com/edamontology/edamontology for these kinds of annotations, but have not written it into the specification yet.
2. A CWL tool description includes a reference to a Docker container (although using Docker is actually optional with CWL) with the idea that you would mainly handle the CWL tool files and download the Docker images on demand.  However, the idea of the tool functionality is "intrinsic" to the container got me thinking that CWL tool descriptions could be provided directly in a Docker image, either as a file with a well known location, or through the upcoming Docker metadata feature (https://github.com/docker/docker/pull/9882)

**Comment by michaelbarton** [comment]
Thanks for your comments @ntijanic and @tetron. They are much appreciated. I
would have responded earlier however we've been discussing bioboxes/rfc#61 in
some detail. I think this issue is close to being resolved now. I think most of
what @tetron wrote is correct, with the exception of the default command, which
we have decided to call this a "task".

The aim of the tasks is that there may be multiple ways you can run the same
tool, for instance through different combinations of provided command line
parameters. Therefore a short read genome assembler may have the signature:

  f: [fastq A], [Maybe insert_size A] -> fasta B

The role of the task is to define different possible algorithms behind the
signature, for example optimised for microbial isolate, single cell or
metagenomic data. We require a default task which should ideally be the
algorithm that does best on most kinds of data, i.e. a good default.

**Comment by max-biodatomics** [comment]
Peter, 
I prefer the way which you described - command line completely specified from CWL. In this case developers have much more flexibility. As and example we are often but not always piped results of aligners to samtool for conversion into bam. 

Also, CWL, should support in specs usage other executes, not only Docker. As an example, I don't know any way how we can use docker containers on hadoop cluster for running efficiently Spark code. So, having option for other executors must be in specks.

**Comment by mr-c** [comment]
@avilella @michaelbarton Any update on this since March?

**Comment by avilella** [comment]
Not that I know, Michael. I've seen bioboxes has recently finalised a cli
version of the boxing process, but no word on CWL interoperability.

On Mon, Oct 26, 2015 at 3:51 PM, Michael R. Crusoe <notifications@github.com

**Comment by michaelbarton** [comment]
No, I'm afraid I haven't had any free time to investigate this further.

**Comment by mr-c** [comment]
Since it has been almost another year I am going to close this issue for now. Feel free to re-open it if progress has been made.
