### ISSUE TITLE
Optional fields that are not provided are "null" not "undefined" & unknown field should be filtered out

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#222]
From discussion, input fields that are not provided are will be missing from the input object for the purposes of evaluating parameter references and expressions.  This is inconsistent in a couple of ways:
1. there is no concept of "valid-but-undefined" in CWL
2. there is 

Any fields which are defined as "optional" but not provided should be set to "null" prior to evaluating parameter references / expressions.

In addition, any fields which are provided in the input but not in the tool's input signature should be filtered out before evaluating parameter references / expressions.

**Comment by mr-c** [comment]
@tetron does that include linked-data metadata provided in the input object that might be intended for flow through?

**Comment by tetron** [comment]
@mr-c not sure.  The problem I'm trying to solve with the 2nd rule is users accessing undeclared inputs through parameter references, resulting in tools which are confusingly broken.

We still need to define rules for handling metadata.

**Comment by pgrosu** [comment]
So the beauty of CWL is that inputs can work independently of each other.  If an input is optional and not instantiated then it should be "self-aware" and remove itself from the graph, before the command is built.  Any dependent fields should also do the same.  

Assigning a null means that a null is a default value of an Optional field, when it should be empty and thus garbage-collected.  I think we need to make sure the user intends what they mean with their CWL file, rather than the cwl-tool trying to guess things about their possible intent.  Otherwise we will have complex CWL files working in concert with unintended consequences.

Could you point me to an example CWL file of some linked metadata that would flow through?  I want to look it and think a bit of such a case, with the possible idea of such metadata transferring itself to the dependent objects before the uninstantiated parent input object removes itself.

Thanks,
~p

**Comment by mr-c** [comment]
@tetron you may want to edit the original post, your 2nd rule is cut off.

**Comment by pgrosu** [comment]
@mr-c I assumed it was a statement negating the 1st rule :)

**Comment by mr-c** [comment]
@ntijanic points out that this is needed for output files as well

**Comment by tetron** [comment]
I think we're good:

        When accepting an input object, all input parameters must have a value.
        If an input parameter is missing from the input object, it must be
        assigned a value of `null` (or the value of `default` for that
        parameter, if provided) for the purposes of validation and evaluation
        of expressions.
