### ISSUE TITLE
Be able to perform read/write operations on input

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/common-workflow-language#380]
hi!

In our specific use case we want to be able to perform read/write operations on input files and directories. Our field is radio astronomy, and we often operate on TeraByte sized datasets. Currently the widely used and informal standard for storing the radio astro data is the measurement set, which is a nested file/directory structure. 

To be able to model our workflows using CommonWL we need to be able to perform read/write operations on these measurement sets. This is currently not possible yet. It 'seems' this is possible though, by setting the `writable: true` flag under the `InitialWorkDirRequirement` extension, example here:

https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/stagefile.cwl#L8

But actually this will copy the file, this to guarantee the 'purity' of the workflow execution. Unfortunately since our datasets are so ridiculously huge this is no option for us. 

As discussed with people involved in maintaining and nurturing CommonWL it is probably best to add this support by the means of an extension.

Possible problems are the introduction of challenges for correctness, not being able to cache results and you can't have input go into more than one node. Unfortunately these are necessary consequences that are hopefully solved by changing the tooling in radio astronomy in the long run. 

Naively I would propose a syntax for this something like this:

```
requirements:
 InputRequirement:
    listing:
      - entry: $(inputs.infile)
        writable: true
```

maybe not that useful, but a short description of measurement sets can be found here: https://casa.nrao.edu/Release3.3.0/docs/UserMan/UserMansu81.html#x94-930002.1.1

to-do list by @mr-c and @tetron 
- [ ] add to v1.1.0-devN
- [ ] add conformance tests
- [ ] add to cwl-upgrade @mr-c

**Comment by mr-c** [comment]
Thank you @gijzelaerr for this overview. 

My understanding is that you want to communicate that some inputs shouldn't be copied (due to their size) and that the same inputs should be modifiable in place. 

1. `InputRequirement` looks very similar to `InitialWorkDirRequirement` and might confuse users
2. I think "do not copy this file" and "this file should be writable" are separate concerns

Combining the two ideas I suggest the following:

1. For CWL v1.0: enhance`InitialWorkDirRequirement` by adding another directive about "do not copy this file" and use a `hint` to indicate this extension
2. When sufficiently mature and adopted by another implementation then the directive could become part of a future release of CWL without needing the custom hint.

Here is one way this could look (I have no particular attachment to `CopyFreeIO` and `copyFree` as names, please suggest alternatives):

```
hints:
  CopyFreeIO: {}

requirements:
 InitialWorkDirRequirement:
    listing:
      - entry: $(inputs.infile)
        writable: true
        copyFree: true
```

**Comment by gijzelaerr** [comment]
A hint is an optional requirement right? So it would be a hint to make sure it is backwards compatible?

To be honest, I find the `writable` label confusing. It means an implicit copy in this case, which only becomes obvious when you read the documentation. Which everybody should do of course, but i think it is confusing. But maybe it is just me who needs to get familiar with the concepts.

**Comment by mr-c** [comment]
Hints are optional, correct. So if an implementation receives a hint it doesn't know about it can safely ignore it and still be able to reason and execute the CWL description. In this case it would do so more slowly and using more disk space than if it did know.

The `copyFree` suggestion above still conforms to CWL v1.0 as naive implementations will just treat it as a piece of random metadata.

Sorry about the confusion with the `writable` label. In the short term we can clarify the documentation, and in the long term a clearer name for that concept could be used instead.

**Comment by gijzelaerr** [comment]
ok yes it makes sense, and i recognise the need for backwards compatibility. 

Is it safe to assume the `copyFree` key is just ignored by existing parsers?

**Comment by mr-c** [comment]
@gijzelaerr correct, `copyFree: true` will look like metadata to existing parsers.

**Comment by gijzelaerr** [comment]
awesome. Well, then your proposal makes the most sense in the current situation.

**Comment by mr-c** [comment]
@gijzelaerr Next step is to hack on `cwltool` to add support for this and see if that works for you all

**Comment by mr-c** [comment]
Update: A version of this was implemented in May by @tetron https://github.com/common-workflow-language/cwltool/pull/317

Usage:
Call `cwltool` with  `--enable-ext`. The CWL description of the tool that needs to be able to edit files inplace should have the following requirement:

```
requirements:
  cwltool:InplaceUpdateRequirement:
    inplaceUpdate: true
  InitialWorkDirRequirement:
    listing:
      - entry: $(inputs.my_dataset)
        writable: true

inputs:
  my_dataset:
    type: File  # or Directory
```
And elsewhere the following namespace definition:
```
$namespaces:
  cwltool: http://commonwl.org/cwltool#

```
Note: using this all inputs that are staged and marked `writable` will be mounted or symlinked so that any edits happen in place.

@tetron What happened to configuring the inplace updates per listing entry?

**Comment by mr-c** [comment]
We will make this available as a regular feature in `v1.1`

**Comment by mr-c** [comment]
@tetron and I agree that a per input flag for inplace updates is not needed

**Comment by mr-c** [comment]
@tetron and I agree that this will be completely optional for v1.1 implementers

**Comment by tetron** [comment]
In progress for v1.1 at https://github.com/common-workflow-language/cwl-v1.1/pull/2
