### ISSUE TITLE
Add successCodes property to CommandLineTool

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#43]
Currently, we recognize success or failure by checking if exit code is zero or not. Some tools (e.g. grep) have successful runs with non-zero exit code. To accommodate this, we should add a `successCodes` property to `CommandLineTool`s (a set of integers with `[0]` being default).

**Comment by tetron** [comment]
There is a more general problem that we haven't specified what success and failure actually mean in the context of the workflow, in fact the reference implementation currently ignores return codes entirely.  What happens instead is that a failed command means either the output or downstream input fail validation, rather than the tool itself being marked as failed.

At minimum, I think want to model two kinds of failure, "permanent failure" and "temporary failure".  Permanent failure should occur because there is some fatal error in the input, while temporary failure is due to transient problems, such as network issues, that may resolve itself after some time without requiring user intervention.

What do you think of this?

```yaml:
successCode: [0, 1]
temporaryFailureCode: [2, 3]
permanentFailureCode: [4, 5]
```

I think the decision whether to default to temporary or permanent failure (if a program yields a code not listed) can be left up the implementation.

In addition to return codes, we should consider if we want to support any other methods for detecting success or failure, such as scanning for specific text in the output (certainly not a draft 2 feature however).

**Comment by ntijanic** [comment]
+1 on temporaryFailureCode. +0 on permanentFailureCode (seems like this will be the default for all engines in one way or another, but it makes sense to list the codes you are sure are not retryable).

**Comment by tetron** [comment]
Implemented and pushed to master.
