### ISSUE TITLE
published cwltool on pip missing schemas

### ISSUE THREAD

**Issue by porterjamesj** [common-workflow-language/common-workflow-language#49]
Trying to run an example from `conformance` with the published version of `cwltool` on pip results in the following:

```
(cwl)vagrant@localhost /vagrant/common-workflow-language/conformance $ cwltool draft-2/cat1-tool.cwl draft-2/cat-job.json
Traceback (most recent call last):
  File "/home/vagrant/cwl/bin/cwltool", line 9, in <module>
    load_entry_point('cwltool==1.0.20150527172438', 'console_scripts', 'cwltool')()
  File "/home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/main.py", line 100, in main
    t = workflow.makeTool(from_url(args.workflow), basedir)
  File "/home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/workflow.py", line 35, in makeTool
    return draft2tool.CommandLineTool(toolpath_object, docpath)
  File "/home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 224, in __init__
    super(CommandLineTool, self).__init__(toolpath_object, "CommandLineTool", docpath)
  File "/home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/process.py", line 39, in __init__
    self.names = get_schema()
  File "/home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/process.py", line 22, in get_schema
    with open(cwl_avsc) as f:
IOError: [Errno 2] No such file or directory: '/home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/schemas/draft-2/cwl-avro.yml'
```

somehow some of the schemas are not being included. Weirdly enough it appears to be only the `.yml` files that are missing:

```
(cwl)vagrant@localhost /vagrant/common-workflow-language/conformance $ ls /home/vagrant/cwl/local/lib/python2.7/site-packages/cwltool/schemas/draft-2/
cwl-context.json  cwl-rdfs.jsonld
```

I'm not sure what's wrong, the [relevant part of setup.py](https://github.com/common-workflow-language/common-workflow-language/blob/5fdd2ad4755d9befb4ce6e0a77c4f9321f711d3c/reference/setup.py#L39) looks right to me, but then again setuptools seems to have an inexhaustible supply of behaviors that surprise and frustrate me.

**Comment by tetron** [comment]
That's frustrating.  I will have to look into it again.

There are two issue that make packaging a challenge:

a) There needs to be some reliable way to package the schema and discover it at runtime.  Installing it alongside the actual code lets makes it possible to use __file__ to get the actual runtime location of the code and then find the schema from there.  Possibly I could install it into a data directory, but I haven't figured out how discovering the install location is supposed to work in that case.

b) It is very very difficult to include files in setuptools that are located outside the setup.py root directory.  Unfortunately, since the schema files are not there _just_ for the benefit of the Python code, I don't want to put them in reference/cwltool/schema, so I have a symlink.  However, older versions of setuptools won't traverse symlinks.  So instead, setup.py has a hack whereby it copies the schema directory to the right place before doing the setup, the restores the symlink afterwards if it was there to begin with.  This usually works, but seems to be kind of flaky.

Any insight into how to make this work better would be appreciated.

**Comment by porterjamesj** [comment]
> There needs to be some reliable way to package the schema and discover it at runtime. Installing it alongside the actual code lets makes it possible to use file to get the actual runtime location of the code and then find the schema from there. Possibly I could install it into a data directory, but I haven't figured out how discovering the install location is supposed to work in that case.

Yeah in general this is how I do it too (just install package data files alongside the code).

> It is very very difficult to include files in setuptools that are located outside the setup.py root directory. Unfortunately, since the schema files are not there just for the benefit of the Python code, I don't want to put them in reference/cwltool/schema, so I have a symlink. However, older versions of setuptools won't traverse symlinks. So instead, setup.py has a hack whereby it copies the schema directory to the right place before doing the setup, the restores the symlink afterwards if it was there to begin with. This usually works, but seems to be kind of flaky.

Ahhh interesting, that makes sense. I can think of a couple possible other ways to mitigate this, neither particularly satisfying:

1. Just maintain two copies of the schema. This is a not very satisfying, but consider the fact that other CWL implementations are not going to be able to symlink to one file in this repo and so they'll end up copying it anyway it's not really that bad.

2. have the symlink go in the other direction so that the file in `reference/` is always real. This is admittedly kind of of weird but it would probably work.

**Comment by tetron** [comment]
I think that I have finally managed to tweak setuptools enough that it correctly includes the schema files in the packaging.  Please review and let me know if you have any more issues.

**Comment by porterjamesj** [comment]
yeah it's been working for me. thank you!
