### ISSUE TITLE
outputBinding in workflow ports

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#53]
It's likely an artifact of entity inheritance, but should be made clear - is it meaningful to keep output binding in workflow output ports only to allow embedded transformations or do we remove the property?

I'd vote for the latter since transformations can be done with a downstream component and "binding" doesn't make much sense in context of a workflow.

**Comment by tetron** [comment]
You're right, it would be more in the spirit of workflows to use `ExpressionTool` to tweak output values.  We could even remove outputEval entirely.  On the other hand, this would make support for nested workflows a little more important, since we might want to define a tool as a command line tool + expression tool which transforms the output.

**Comment by tetron** [comment]
Committed schema changes so that outputBinding is only a property of CommandLineTool.  Please review and re-open ticket if you have any concerns.
