### ISSUE TITLE
UserGuide.html in draft-3 non existent

### ISSUE THREAD

**Issue by stellargo** [common-workflow-language/common-workflow-language#538]
![screen shot 2017-11-01 at 9 46 39 pm](https://user-images.githubusercontent.com/27735438/32284779-3e3e3836-bf4e-11e7-80be-aa47aedead8f.png)
The user guide link at https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-3/README.md points to UserGuide.html which is not available and shows a file not found error

**Comment by stellargo** [comment]
Can I work on resolving this issue?

**Comment by mr-c** [comment]
Hello @stellargo and thanks for the report. From the website http://www.commonwl.org/draft-3/ that page gets rendered so that the link is http://www.commonwl.org/draft-3/UserGuide.html which works for me.

We should update the draft-3/README to emphasis that this is an outdated version of the specs and drop the link to the draft-3 user guide; adding links and encouragement to view the v1.0 versions instead.

> Can I work on resolving this issue?
Thanks for offering, sure!
