### ISSUE TITLE
Site-specific dependencies for tools

### ISSUE THREAD

**Issue by claresloggett** [common-workflow-language/common-workflow-language#70]
I frequently run pipelines on a cluster where using Docker is difficult and the canonical way to access a tool is via environment modules. 

A useful thing for me to be able to do in this situation is run e.g. `module load samtools/1.1.18` before running the samtools tool. 

Is there a sensible way to incorporate this kind of requirement into the CWL tool declaration, or some other part of CWL? Conceptually this requirement probably needs to be specified (or at least able to be overridden) by the person running the workflow, who knows the details of their site.

NB In some cases I could load all modules before running the pipeline, but if I'm using tools which have conflicting version dependencies, or if I'm using a workflow engine which distributes parallel jobs to the cluster, I want to be able to load modules on a per-step basis.

**Comment by mr-c** [comment]
I think an additional Requirement type would work here. The tricky bit is that module names are not standardized at all :-P

Thoughts @tetron @ntijanic @jmchilton ?

**Comment by ntijanic** [comment]
I'd suggest the approach described in #32: specifying a requirement to match tool version, but not specifying _how_. 

In addition to this, `DockerRequirement` or something like `myorg:PackageRequirement` can be placed in the hints section to describe the "how" part.

For the case described above, it would mean that the "executor" engine would need to recognize the `myorg:PackageRequirement` or be configured to run `module load toolkit/version` commands before each job, based on the `PackageRequirement`.

**Comment by tetron** [comment]
As @mr-c and @ntijanic have mentioned already, this is exactly the kind of problem that requirement sections are intended to solve.  Someone with experience using environment modules should propose a design.

Running the module loads ahead of time actually won't work because the specification requires that tools run in a clean environment for portability.

There is an interesting question of how to best to express a situation where a tool's dependencies can be satisfied more than one way (for example, a python package, distribution package, or docker image).

Also, I suspect we may want to add "override" requirements which have top down precedence instead of bottom up.

**Comment by mr-c** [comment]
You can now add or override requirements in the job input document in the current `cwltool`. We forgot to document for the 1.0 release of the standard, but it will be in the next release.

**Comment by mr-c** [comment]
Closing in favor of #210 / #304
