### ISSUE TITLE
Conformance tests 121 and 172 require inconsistent behaviors for `glob` field

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#801]
The current sorting behavior of `glob`, that is implicitly required by the conformance tests 121 and 172, seems inconsistent.

The conformance test 121 (consists of [glob_test.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/glob_test.cwl) and [empty.json](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/empty.json)) requires the result of `glob` should be sorted.
On the other hand, the conformance test 172 (consists of [output-arrays-file-wf.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/output-arrays-file-wf.cwl) and [output-arrays-file-job.json](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/output-arrays-file-job.json)) requires that the result should not be sorted.

I guess such a difference is caused by the different types of the values of `glob` fields (i.e., `"*"`: `string` and `["moo", "cow"]`: `array<string>`).
However, such a behavior makes us confusing, especially when an expression is occurred in `glob` fields (that may be a string or an array of string!).

IMO it is better to make the results of the conformance test 172 sorted.

**Comment by mr-c** [comment]
Hello @tom-tan and thank you for your issue. I think you will find the discussion in https://github.com/common-workflow-language/common-workflow-language/issues/440 relevant as it contains our plans to clarify the situation in CWL v1.1

First, to explain test 172:
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/output-arrays-file-wf.cwl#L51
When this workflow is run using [output-arrays-file-job.json](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/output-arrays-file-job.json) then `$(inputs.i)` resolves to an array of strings: `["moo", "cow"]`. Each of these is treated as a single `glob` entry. If any of them matched multiple files then within that entry the results should be sorted as already specified in POSIX. However the collections of `glob` entries results are not sorted again. Thus the correct order for this example is first the file named `moo` and then the file named `cow`.

Since this is the same thing we are discussing over in https://github.com/common-workflow-language/common-workflow-language/issues/440 I am going to close this issue.

@tom-tan Please feel free to share your viewpoint there!
