### ISSUE TITLE
Official CWL Python projects: No new Python 2.7 supporting releases after 2020-01-01

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#828]
I make this issue here because most official tools in the CWL project are written in Python.

I found that CI tester for [common-workflow-language/schema_salad](https://github.com/common-workflow-language/schema_salad) show the following deprecation messages:

```console
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

```console
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
```

```console
========================== deprecated python version ===========================
You are using Python 2.7.14, which will no longer be supported in pytest 5.0
```

```console
========================== deprecated python version ===========================
You are using Python 3.4.6, which will no longer be supported in pytest 5.0
```

My question is when to drop the support for old Python versions for official CWL tools such as `cwltool` and `schema_salad`.

One possible answer is after the old Python versions reach their end of life.

However, it would be nice if the CWL project previously announced when to drop them from our support.
It enables the users to prepare migration to the newest version of Python before actually dropping the support.

**Comment by mr-c** [comment]
Please note that this conversation is about what version of Python the CWL community supported reference runner and related tools should be in.

CWL `CommandLineTools` can describe programs written in any POSIX/Linux compatible language; which means any version of the Python language, or Perl, Java, D, Ruby, Fortran, C/C++, etc..

Back to the issue at hand, @tom-tan Thank you for raising this and I agree that it needs addressing.

Pragmatically we have no dedicated resources for Python 2.7 compatibility.

Personally I would like us to drop Python 2.7 testing ASAP and remove all Python 2.7 compatibility shims soon after.

The next decision will be to pick a version of Python 3 to standardize on, to gain access to the new features. My personal preference is that we pick a very recent version of Python 3 since we are unlikely to revisit this decision again for a while.

I would suggest Python 3.7 as that is the [only version of Python 3](https://packages.debian.org/search?suite=buster&searchon=names&keywords=python3.) that will be in the next version of Debian, Debian 10 (codename "Buster").

**Comment by tom-tan** [comment]
Thank you for clarifying the issue, @mr-c!

Yes.
This issue is about the languages in which `cwltool` and other tools, that are provided by the CWL project, are written.
It is **not** about the languages in which `CommandLineTool`, that are supported by CWL specification, are written.

> I would suggest Python 3.7 as that is the [only version of Python 3](https://packages.debian.org/search?suite=buster&searchon=names&keywords=python3.) that will be in the next version of Debian, Debian 10 (codename "Buster").

Good idea.
By deciding to support only the latest version, we can write simpler and more robust code by using the functions that have been introduced in the newer versions.

> Personally I would like us to drop Python 2.7 testing ASAP and remove all Python 2.7 compatibility shims soon after.

IMO it would be nice if we decide and announce the fixed date that ends support for Python 2.7 rather than directly dropping Python 2.7.
It is less confusion for users and makes easier for users to plan the migration before the fixed date.

I guess a half year is enough for migration but I am not sure for a shorter period.

**Comment by tetron** [comment]
Half a year to phase out 2.7 would be September, but we should get feedback from implementations that depend on cwltool.  For our part, arvados-cwl-runner now passes tests with Python 3.5.  However, there is also Toil, Airflow, Galaxy, and probably some others.

For minimum Python 3 version, I would strongly prefer to base on 3.5, as that's the version in Debian 9 (3.5.3) and Ubuntu 16.04 LTS (3.5.1).

**Comment by geoffjentry** [comment]
One could argue that projects not taking a hard stance regarding upgrading to Python 3 is precisely why we’re having this discussion a decade after the release of Python 3 :)

**Comment by mr-c** [comment]
Ubuntu 16.04 LTS end of life is April 2021 (2.5 years from now) 
Ubuntu 18.04 LTS end of life is April 2023 (4.5 years from now) and it include Python 3.7

Once Debian 10 is released in a few months then there will only be [12 more months of security updates for Debian 9](https://www.debian.org/security/faq#lifespan)

The popular Ubuntu PPA for getting all versions of Python has Python 3.7 for Ubuntu 16.04:
https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa?field.series_filter=xenial

**Comment by mr-c** [comment]
The current release of all official CWL community Python projects on January 1st, 2020 will be the last to support Python 2.7 https://github.com/common-workflow-language/cwltool/issues/1107
