### ISSUE TITLE
[cwl workflow steps] explicit I/O relationship, workflow

### ISSUE THREAD

**Issue by r06942072** [common-workflow-language/common-workflow-language#841]
Link: https://github.com/r06942072/CWL_Common-Workflow-Language/blob/dev/final-workflow.cwl
I met some problems when using CWL workflow

I know that the steps order is decided by input/output relationship, so I fed **out_tree** in setup_tree to **in_dir** in copy2data.

However, I wonder if there is a way to explicitly specify the order of workflow.
Like 
Step1.  setup_tree
Step2.  download_genomic
........

Thank you

Best,
Chun-Hung

**Comment by kaushik-work** [comment]
Hi @r06942072 , CWL is declarative in nature, so you can't directly control these steps (and should not have to, like in functional programming).

The reason why you have an order of operations is because there is a dependency, perhaps hidden, in those steps. In CWL, like in functional paradigms, these dependencies should naturally come out of the way the steps are connected. If there is no connection from A to B, then B does not depend on A and it does not need to start after A.
