### ISSUE TITLE
Why did not find output file with glob pattern when run cwl-runner

### ISSUE THREAD

**Issue by honghh2018** [common-workflow-language/common-workflow-language#909]
Hi @ALL,
     Thanks to develop the great tools for data analysis.
      The issue occurred as following when my cwl runned through linux platform.
       The cwl file saying below:
      
![image](https://user-images.githubusercontent.com/41668708/86469976-0e773600-bd6d-11ea-847f-b6701a9b0a1a.png)
     The yml files saying below:
      
![image](https://user-images.githubusercontent.com/41668708/86470055-36669980-bd6d-11ea-8aa7-8b9c3de5e167.png)

       The error showing below:
![image](https://user-images.githubusercontent.com/41668708/86469871-de2f9780-bd6c-11ea-8764-de49ef30c310.png)
   What happen on this case, and i want to get the output folder's file, in which no setting on the script location but on the directory that i want to set
    Any advices should be appreciate!

**Comment by mr-c** [comment]
Hello @honghh2018 !

Since `hisat2-build` is a common command, I would first recommend seeing how other people handle it: https://github.com/search?q=hisat2-build+cwlVersion&type=Code

About the error: All outputs must be in the working directory. Consider using https://www.commonwl.org/user_guide/15-staging/index.html to stage the index and the you can `glob` on to that relative path.

**Comment by honghh2018** [comment]
Thanks for the nice reply.
 I would try you proposal at soon.

**Comment by mr-c** [comment]
I'm going to close this issue. @honghh2018 or anyone else, please feel free to comment or re-open this issue if you have no success.
