### ISSUE TITLE
need academic HPC cluster implementation

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#98]
Perhaps using https://en.wikipedia.org/wiki/DRMAA ?

**Comment by yvdriess** [comment]
I am close to making CWL work for `precipes` (https://github.com/yvdriess/precipes). The current execution engine already works on a cluster configuration (either via mpirun or plain sockets) with good linear speedups.

In other words: pending!

**Comment by mr-c** [comment]
This is fantastic news, thanks!

On Tue, Aug 11, 2015, 06:56 Yves Vandriessche <notifications@github.com>
wrote:

> I am close to making CWL work for precipes (
> https://github.com/yvdriess/precipes). The current execution engine
> already works on a cluster configuration (either via mpirun or plain
> sockets) with good linear speedups.
>
> In other words: pending!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/common-workflow-language/common-workflow-language/issues/98#issuecomment-129884304>
> .
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by tetron** [comment]
Any chances for DRMAA or other job scheduler (PBS, SGE, Condor, Torque...) support?

**Comment by yvdriess** [comment]
Yes and no, `precipes` should work with those schedulers, as it can run using MPI as a simple binary:
`mpirun -f $HOSTFILE -rr -n $NUM_NODES ./precipes my_workflow.json sample_1 sample_2 sample_3`
In other words, you submit the whole shebang as one batch job.

However, `precipes` does not support these job schedulers directly, directly as in submitting individual jobs for individual workflow steps at runtime. In principle, direct support for such schedulers is perfectly possible; CnC is used inside the precipes engine to coordinate 'if' and 'when' something should execute, then simply performs a system call. Direct support of the job schedulers would in principle simply mean submitting a job instead of directly doing the system call. We are looking into doing something similar using Mesos to achieve resource-aware scheduling.  If you would really love direct job scheduler support, please contact me, we can work on this if we can point to 'customers' that need such feature.

**Comment by mr-c** [comment]
[Notes from 2016-02-17 meeting](https://docs.google.com/document/d/1l_03K9hRh4_D50__qsH0-6EQaD1O1glZsomwUZqQgGc/edit?usp=sharing)

Relevant links:
https://github.com/BD2KGenomics/toil/issues/682
https://github.com/BD2KGenomics/toil/blob/master/src/toil/cwl/cwltoil.py#L248
https://github.com/curoverse/arvados/blob/master/sdk/cwl/arvados_cwl/__init__.py#L331

**Comment by mr-c** [comment]
Toil solved this, thanks all!

https://github.com/BD2KGenomics/toil
